### ISSUE TITLE
Productizing bot deployment

### ISSUE THREAD

**Issue by dpaiton** [delvtech/agent0#1541]
# Tasks
- [ ] write a readme for deploying bots (@slundqui)
- [ ] "one-click" solution to deploying checkpoint & invariant bots (tbd after readme)
- [x] setup rollbar monitoring & notifications
  - [ ] flag or label or something to make sure these errors can be filtered (@slundqui )
  - [ ] discord channel that ingests notifs (@wakamex)
- [ ] write up a playbook for when things fail (@jrhea)
- [ ] setup credential storage (@mcclurejt)
- [ ] setup & distribute lastpass credentials for pauser (@jalextowle )
- [ ] review invariant checks (@jalextowle @slundqui )

# Responsibility
- @ryangoree @slundqui @jalextowle @dpaiton @wakamex @mcclurejt @jrhea  all responsible for monitoring checkpoint & invariant bots

## Importance (priority)
1. invariant fails (page @jalextowle @jrhea @mcclurejt )
2. checkpoint bot tries to checkpoint & fails
3. checkpoint bot goes down
4. invariant goes down

# Top priorities for mainnet
- checkpoint bot & invariance check bot
  - runs
  - reporting system for when it goes down
  - secure credential management
  - documentation on how to (re)deploy bots

# bots to consider
- checkpoint
- invariance check
- lpandarb
  - this should be added after the other two are working well

# documentation
  - README.md in infra

# uptime monitoring
  - easily-accessible location for cloud machine address & status
  - easily-accessible portal to view all deployed bot wallets

# error reporting & notifications
  - notifications to critical team when bots go down (rollbar?)
  - system in place to assign responsibility for who should handle errors

# easy start & restart
  - minimal steps to deploy new bots on a pool
  - ideally would be able to run out in a mainnet fork on aws instance

# containerized deployment
  - setup flag for "service bots"

# invariant checks
  - rollbar filters for each check type

# credentials storage
  - privileged access to private keys for bots
  - whoever sets this up is fine with making calls -- lets prioritize "easy" and "safe"
     - ideally use a free service, but if not then fine
  - easiest to use env vars
  - lastpass credentials for pauser

# continuous deployment
  - nice to have
  - when infra pushes a release we deploy bots on a mainnet fork in AWS?
  - almost-continuous deployment -- make it easy for a dev to manually test deployment

# current status -- checkpoint bot:
  - running in docker container
    - docker can restart automatically on failure (easily set up)
  - passes credentials via env variables set in infra repo
    - registry address, rpc uri (points to anvil node), private key, rollbar api key

**Comment by slundqui** [comment]
Readme on deploying bots within https://github.com/delvtech/hyperdrive-infra/pull/119

**Comment by slundqui** [comment]
Something to note is that rollbar doesn't have a great way to log "this process is dead". May need a separate "monitoring" container that logs errors if the service bots containers are stopped, or we allow docker to always restart. Even then, if the aws machine goes down, there's no way of logging an error
